### ISSUE TITLE
CNF after adding handler.sql

### ISSUE THREAD

**Issue by pekeler** [duct-framework/docs#8]
In the guide, [after](https://github.com/duct-framework/docs/blob/master/GUIDE.rst#adding-a-query-route) adding the new dependency on handler.sql and restarting the REPL, `(go)` gives me
```
Syntax error (ClassNotFoundException) compiling new at (jsonista/core.clj:80:38).
com.fasterxml.jackson.core.exc.InputCoercionException
```
Should I change all the dependency versions like they're in the guide instead of using the generated ones?

**Comment by weavejester** [comment]
Could you give me your `project.clj` file so I can investigate?

**Comment by pekeler** [comment]
https://gist.github.com/pekeler/58b2639f7cb5439048aebd69fbf5a6ca

**Comment by weavejester** [comment]
I've fixed the issue. You can either run `lein new duct ...` again, or update the version of the `duct/module.web` dependency to `0.7.3`. Then it should work as expected.

**Comment by pekeler** [comment]
That works. Thank you!
